import Link from "next/link";
export function Badge({ status }: { status:string }) { const s=status.toUpperCase(); const color=s.includes("SUCCESS")||s==="ONLINE"?"var(--green)":s.includes("FAIL")||s.includes("REVOK")||s.includes("CANCEL")?"var(--red)":s.includes("RUN")||s.includes("BUILD")?"var(--yellow)":"var(--blue)"; return <span style={{ display:"inline-flex",alignItems:"center",gap:6,color,background:`${color}18`,border:`1px solid ${color}40`,borderRadius:99,padding:"4px 8px",fontSize:10,fontWeight:800,letterSpacing:'.06em' }}><span style={{ width:5,height:5,borderRadius:'50%',background:color }} />{s.replaceAll("_"," ")}</span>; }
export function Card({ children, style }: { children:React.ReactNode; style?:React.CSSProperties }) { return <section className="dp-card" style={{ padding:20, ...style }}>{children}</section>; }
export function Stat({ label, value, detail, accent="var(--blue)" }: { label:string; value:string|number; detail?:string; accent?:string }) { return <Card style={{ position:"relative", overflow:"hidden" }}><div style={{ position:"absolute",right:0,top:0,width:80,height:80,background:`radial-gradient(circle,${accent}25,transparent 70%)` }} /><div className="dp-kicker">{label}</div><div style={{ fontSize:28,fontWeight:800,letterSpacing:"-.06em",marginTop:13 }}>{value}</div>{detail && <div style={{ color:"var(--muted)",fontSize:11,marginTop:7 }}>{detail}</div>}</Card>; }
export function SectionTitle({ title, href, action }: { title:string; href?:string; action?:string }) { return <div style={{ display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:15 }}><h2 style={{ fontSize:15,margin:0,letterSpacing:"-.02em" }}>{title}</h2>{href && <Link href={href} style={{ color:"var(--muted)",fontSize:11,fontWeight:700 }}>{action ?? "View all"} →</Link>}</div>; }
export function Empty({ title, text, href, action }: { title:string;text:string;href?:string;action?:string }) { return <div style={{ textAlign:"center",padding:"46px 20px",border:"1px dashed var(--line)",borderRadius:10,color:"var(--muted)" }}><div style={{ fontSize:25,color:"#5e6b7e",marginBottom:12 }}>◌</div><strong style={{ color:"var(--text)",display:"block",marginBottom:6 }}>{title}</strong><div style={{ fontSize:12 }}>{text}</div>{href && <Link className="dp-btn dp-btn-primary" href={href} style={{ display:"inline-block",marginTop:18,fontSize:12 }}>{action ?? "Get started"}</Link>}</div>; }
export function formatDate(value?:string|null) { return value ? new Date(value).toLocaleString([], { month:"short",day:"numeric",hour:"2-digit",minute:"2-digit" }) : "—"; }

export function PageHeader({ eyebrow, title, description, action }: { eyebrow:string; title:string; description?:string; action?:React.ReactNode }) { return <header style={{ display:"flex", justifyContent:"space-between", gap:20, alignItems:"flex-start", marginBottom:28, flexWrap:"wrap" }}><div><div className="dp-kicker" style={{ marginBottom:10 }}>{eyebrow}</div><h1 style={{ margin:0, fontSize:"clamp(25px,3vw,34px)", letterSpacing:"-.055em" }}>{title}</h1>{description && <p style={{ margin:"9px 0 0", color:"var(--muted)", maxWidth:680, lineHeight:1.6 }}>{description}</p>}</div>{action}</header>; }
