import Link from "next/link";
import type { Metadata } from "next";
export const metadata: Metadata = { title: "Getting started | DeployPilot", description: "Import a GitHub repository and deploy it with your team's Docker worker." };
const steps = [
  ["Sign in with GitHub", "Choose your account. Create a team to share repositories: owners and admins manage access, developers deploy, and viewers read."],
  ["Import your repository", "Open Repositories, connect the DeployPilot GitHub App and select its repository access. Load repositories in the dashboard. An organization owner must connect an organization installation."],
  ["Configure the application", "Choose Configure and deploy. Select a Dockerfile, branch and build profile; set the container port, health path and environment. Add required build or runtime secrets in environment settings."],
  ["Connect your worker", "On Workers, select the repository and register a worker. Copy its one-time environment to a private file on the machine. Install Docker with Linux containers, Node.js 22 and pnpm 9.15, then follow the dashboard's worker setup instructions."],
  ["Deploy and verify", "Keep the worker online, start a deployment, and follow its stages and logs. Check its health and local runtime address. Cancel, retry, stop or restart through the dashboard."],
];
export default function GettingStarted() {
  return <main style={{ maxWidth: 1000, margin: "auto", padding: "32px clamp(20px,5vw,60px) 64px" }}>
    <nav aria-label="Guide navigation" style={{ display: "flex", flexWrap: "wrap", justifyContent: "space-between", gap: 12 }}><Link className="dp-btn" href="/">← DeployPilot</Link><Link className="dp-btn dp-btn-primary" href="/login">Sign in with GitHub</Link></nav>
    <div className="dp-kicker" style={{ color: "var(--green)", marginTop: 42 }}>Public beta</div><h1 style={{ fontSize: "clamp(32px,5vw,52px)", letterSpacing: "-.05em" }}>Deploy with your own Docker worker</h1>
    <p style={{ color: "var(--muted)", lineHeight: 1.7 }}>No custom domain is needed for this dashboard. Each team provides its own worker; DeployPilot does not provision or pay for compute.</p>
    <ol style={{ paddingLeft: 24 }}>{steps.map(([title, description]) => <li key={title} style={{ paddingLeft: 8, margin: "26px 0" }}><h2 style={{ fontSize: 20 }}>{title}</h2><p style={{ color: "var(--muted)", lineHeight: 1.7 }}>{description}</p></li>)}</ol>
    <section className="dp-card" style={{ padding: 24, marginTop: 32 }}><h2>Before connecting a worker</h2><p style={{ lineHeight: 1.7 }}>Use a dedicated machine for your team and run only repositories you trust. Workers execute repository code. Keep the Docker daemon and credentials private; teams should use separate hosts.</p><p style={{ color: "var(--muted)", lineHeight: 1.7 }}>Download worker setup from <a href="https://github.com/porwalakshat124/deploypilot">GitHub</a>. Only worker credentials belong on that machine; database, GitHub App and provider keys stay on the API server. Rotate or revoke worker credentials in the dashboard.</p></section>
    <section style={{ marginTop: 32 }}><h2>App addresses and beta limits</h2><p style={{ color: "var(--muted)", lineHeight: 1.7 }}>Containers run on the team worker; their default addresses are local to that machine. Vercel serves this dashboard. Public app access requires routing supplied by the team, and workers must stay online.</p><p style={{ color: "var(--muted)", lineHeight: 1.7 }}>One build runs at a time per worker. Rollback depends on the worker retaining its images. AI diagnosis is disabled. This beta passed bounded recovery and load tests; independent security review is still outstanding.</p></section>
    <section style={{ marginTop: 32 }}><h2>Your repositories and data</h2><p style={{ color: "var(--muted)", lineHeight: 1.7 }}>GitHub handles your password and lets you choose repository access. DeployPilot stores account and team records, repository metadata, deployment configuration, logs and encrypted environment secrets. Build source is sent to your selected worker. Avoid printing secrets in application output.</p><p style={{ color: "var(--muted)", lineHeight: 1.7 }}>Searchable logs retain 30 days; archived logs retain 90 days. Recovery backups can retain older records until operator cleanup. Revoke the GitHub installation to stop future access. For beta feedback or data-removal requests, <a href="https://github.com/porwalakshat124/deploypilot/issues">open an issue</a> without private data, credentials or build logs.</p></section>
    <section style={{ marginTop: 32 }}><h2>Invitations and notifications</h2><p style={{ color: "var(--muted)", lineHeight: 1.7 }}>Team owners share invitation links directly. Use dashboard deployment status and logs as your source of truth: email delivery depends on the operator's verified sender and is not guaranteed in this beta.</p></section>
    <Link className="dp-btn dp-btn-primary" style={{ marginTop: 24 }} href="/dashboard/repositories">Import a repository →</Link>
  </main>;
}
